name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MinGW-w64 (Brecht Sanders)
        run: |
          curl -LO https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0win32-12.0.0-msvcrt-r1/winlibs-x86_64-win32-seh-gcc-14.2.0-llvm-19.1.3-mingw-w64msvcrt-12.0.0-r1.zip
          7z x winlibs-x86_64-*.zip -oC:\mingw
        shell: cmd

      - name: Add MinGW to PATH
        run: echo "C:\mingw\mingw64\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH
        shell: powershell

      - name: Compile resource file
        run: windres resizerkey.rc -O coff -o resizerkey_res.o

      - name: Compile static EXE
        run: g++ resizerkey.cpp resizerkey_res.o -o resizerkey.exe -mwindows -static -static-libgcc -static-libstdc++

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: resizerkey.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
